# Use an official Node runtime as a parent image
FROM node:14.16.1-alpine3.13

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the remaining application files to the container
COPY . .

# Build the application
RUN npm run build

# Expose port 3000 to the host
EXPOSE 3000

# Start the application
CMD [ "npm", "start" ]
